<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
type Match={id:string;blueName:string;redName:string;weightCategory:string;side:string;status:string;matchNumber:number;round:number}
type Court={court:number;current:Match|null;upcoming:Match[]}
const data=ref<{tournament:null|{id:string;name:string;courts:number;revision:number};courts:Court[]}>({tournament:null,courts:[]})
const loading=ref(true);const error=ref('');const justUpdated=ref(false);let timer:number|undefined;let updateTimer:number|undefined
const tournamentId=new URLSearchParams(location.search).get('tournamentId')
async function load(){try{const q=tournamentId?`?tournamentId=${encodeURIComponent(tournamentId)}`:'';const response=await fetch(`/api/v1/public/ovr${q}`);if(!response.ok)throw new Error('دریافت برنامه زمین‌ها ناموفق بود');const next=await response.json();if(data.value.tournament&&next.tournament?.revision!==data.value.tournament.revision){justUpdated.value=true;if(updateTimer)clearTimeout(updateTimer);updateTimer=window.setTimeout(()=>justUpdated.value=false,1200)}data.value=next;error.value=''}catch(e:any){error.value=e?.message||'ارتباط با سرور برقرار نشد'}finally{loading.value=false}}
const roundLabel=(m:Match)=>m.side==='final'?'فینال':m.side==='semifinal'?'نیمه‌نهایی':`دور ${m.round}`
const courtLetter=(court:number)=>String.fromCharCode(64+Math.max(1,Math.min(26,court)))
const viewportWidth=ref(window.innerWidth)
const currentNameSize=(name:string)=>{const count=data.value.courts.length;const compact=viewportWidth.value<800;const base=compact?(count<=2?1.35:count===3?1.12:.95):(count<=2?2:count===3?1.55:1.15);const factor=compact?(name.length>18?.5:name.length>14?.58:name.length>10?.68:1):(name.length>20?.68:name.length>16?.78:name.length>12?.9:1);return{fontSize:`${Math.max(.7,base*factor)}rem`}}
const nextNameSize=(name:string)=>{const compact=viewportWidth.value<800;const base=compact?.68:.82;const factor=name.length>20?.7:name.length>16?.78:name.length>12?.88:1;return{fontSize:`${Math.max(.52,base*factor)}rem`}}
const viewportHeight=ref(window.innerHeight)
const upcomingLimit=computed(()=>3)
const clock=ref('');function tick(){clock.value=new Date().toLocaleTimeString('fa-IR',{hour:'2-digit',minute:'2-digit'})}
const syncViewport=()=>{viewportHeight.value=window.innerHeight;viewportWidth.value=window.innerWidth}
onMounted(()=>{load();tick();window.addEventListener('resize',syncViewport);timer=window.setInterval(()=>{load();tick()},2000)});onUnmounted(()=>{window.removeEventListener('resize',syncViewport);if(timer)clearInterval(timer);if(updateTimer)clearTimeout(updateTimer)})
const hasMatches=computed(()=>data.value.courts.some(c=>c.current||c.upcoming.length))
</script>
<template>
  <main dir="rtl" class="ovr-stage flex h-screen max-h-screen flex-col overflow-hidden p-2.5 text-white lg:p-4" :class="{'ovr-updated':justUpdated}">
    <header class="scoreboard-header relative z-10 mb-2.5 flex shrink-0 items-center justify-between gap-3 overflow-hidden rounded-xl border border-slate-700 px-4 py-2.5 lg:px-5"><div class="flex min-w-0 items-center gap-3"><div class="tkd-mark flex h-10 w-10 shrink-0 items-center justify-center rounded-lg text-sm font-black tracking-tighter">TKD</div><div class="min-w-0"><div class="text-[10px] font-bold tracking-widest text-slate-400 lg:text-xs">سامانه نمایش زمین مسابقات</div><h1 class="truncate text-lg font-black lg:text-2xl">{{data.tournament?.name||'در انتظار شروع تورنمنت'}}</h1></div></div><div class="flex shrink-0 items-center gap-2.5"><Transition name="flash"><span v-if="justUpdated" class="hidden rounded-md bg-emerald-500/15 px-2 py-1 text-[10px] font-bold text-emerald-300 sm:inline">به‌روز شد</span></Transition><div class="live-pill flex items-center gap-1.5 rounded-md border border-red-500/30 bg-red-500/10 px-2.5 py-1.5 text-xs font-bold text-red-300"><span class="h-2 w-2 animate-pulse rounded-full bg-red-500"></span>زنده</div><div class="text-lg font-black tabular-nums lg:text-2xl">{{clock}}</div></div></header>
    <p v-if="error" class="mb-4 rounded-xl bg-rose-500/15 p-3 text-rose-200">{{error}}</p>
    <div v-if="loading" class="grid flex-1 place-items-center text-slate-400">در حال دریافت برنامه مسابقات…</div>
    <div v-else-if="!data.tournament||!hasMatches" class="grid flex-1 place-items-center"><div class="text-center"><div class="tkd-empty mx-auto grid h-20 w-20 place-items-center rounded-full text-xl font-black">TKD</div><h2 class="mt-4 text-2xl font-bold">مسابقه‌ای در صف اجرا نیست</h2><p class="mt-2 text-slate-400">با آماده‌شدن جدول مسابقات، اطلاعات زمین‌ها خودکار نمایش داده می‌شود.</p></div></div>
    <section v-else class="courts-grid relative z-10 grid min-h-0 flex-1 gap-2.5" :class="data.courts.length===1?'courts-1':data.courts.length===2?'courts-2':data.courts.length===3?'courts-3':'courts-4'">
      <article v-for="court in data.courts" :key="court.court" class="court-card flex min-h-0 flex-col overflow-hidden rounded-2xl border border-slate-700 bg-[#0b111c] shadow-xl">
        <header class="court-header shrink-0 px-3 py-2.5 text-center"><h2 class="court-title text-2xl font-black tracking-tight lg:text-3xl">زمین {{court.court}} <span class="mx-1 text-white/35">/</span> {{courtLetter(court.court)}}</h2></header>
        <Transition name="match" mode="out-in"><div v-if="court.current" :key="court.current.id" class="current-match shrink-0 p-2.5 lg:p-3">
          <div class="current-meta mb-2 text-center"><div class="match-number text-3xl font-black leading-none text-white lg:text-4xl">{{court.current.matchNumber}}</div><div class="match-weight text-base font-extrabold leading-tight text-amber-300 lg:text-lg">وزن {{court.current.weightCategory}}</div><div class="mt-1 inline-flex rounded border border-slate-700 bg-slate-800 px-2.5 py-0.5 text-[10px] font-bold text-slate-300 lg:text-xs">{{roundLabel(court.current)}}</div></div>
          <div class="versus-grid grid grid-cols-[1fr_auto_1fr] items-stretch gap-2 rounded-xl bg-slate-950/50 p-2">
            <div class="fighter fighter-blue flex min-h-14 items-center justify-center rounded-lg px-2 py-2 text-center lg:min-h-16"><div class="fighter-name font-black" :style="currentNameSize(court.current.blueName)" :title="court.current.blueName">{{court.current.blueName}}</div></div>
            <div class="vs-mark flex items-center text-xl font-black text-slate-500">VS</div>
            <div class="fighter fighter-red flex min-h-14 items-center justify-center rounded-lg px-2 py-2 text-center lg:min-h-16"><div class="fighter-name font-black" :style="currentNameSize(court.current.redName)" :title="court.current.redName">{{court.current.redName}}</div></div>
          </div>
        </div>
        <div v-else class="grid flex-1 place-items-center p-4 text-center text-sm text-slate-500">بازی دیگری برای این زمین وجود ندارد.</div>
        </Transition>
        <div v-if="court.upcoming.length" class="upcoming-block min-h-0 flex-1 border-t border-slate-700 p-2 lg:p-2.5"><h3 class="mb-1.5 text-center text-[10px] font-black tracking-wide text-slate-400 lg:text-xs">بازی‌های بعدی</h3><div class="upcoming-list grid gap-1.5"><div v-for="(m,i) in court.upcoming.slice(0,upcomingLimit)" :key="m.id" class="upcoming-row grid grid-cols-[minmax(0,1fr)_4.5rem_minmax(0,1fr)] items-stretch gap-1.5 rounded-lg p-1.5 lg:grid-cols-[minmax(0,1fr)_5.2rem_minmax(0,1fr)]" :class="i===0?'upcoming-next':'bg-slate-900'"><div class="next-player next-blue flex min-h-10 items-center justify-center rounded-md px-1 py-1.5 text-center font-extrabold" :style="nextNameSize(m.blueName)" :title="m.blueName">{{m.blueName}}</div><div class="next-meta flex flex-col items-center justify-center text-center"><div class="text-lg font-black leading-none lg:text-xl">{{m.matchNumber}}</div><div class="mt-0.5 text-[10px] font-bold leading-none text-amber-300 lg:text-xs">وزن {{m.weightCategory}}</div></div><div class="next-player next-red flex min-h-10 items-center justify-center rounded-md px-1 py-1.5 text-center font-extrabold" :style="nextNameSize(m.redName)" :title="m.redName">{{m.redName}}</div></div></div></div>
      </article>
    </section>
    <footer class="relative z-10 mt-1.5 shrink-0 text-center text-[9px] text-slate-600 lg:text-[10px]">به‌روزرسانی خودکار هر ۲ ثانیه · سامانه برگزاری مسابقات تکواندو</footer>
  </main>
</template>
<style scoped>
.ovr-stage{position:relative;background:#070b12;background-image:linear-gradient(#ffffff05 1px,transparent 1px),linear-gradient(90deg,#ffffff05 1px,transparent 1px);background-size:42px 42px}
.ovr-stage:before,.ovr-stage:after{content:"";position:fixed;top:0;bottom:0;width:5px;z-index:0}.ovr-stage:before{right:0;background:#1264d6}.ovr-stage:after{left:0;background:#dc174b}.scoreboard-header{background:#101722}.scoreboard-header:before{content:"";position:absolute;right:0;top:0;bottom:0;width:6px;background:#1264d6}.scoreboard-header:after{content:"";position:absolute;left:0;top:0;bottom:0;width:6px;background:#dc174b}.tkd-mark,.tkd-empty{border:2px solid #e5e7eb;background:#111827;box-shadow:inset 4px 0 #dc174b,inset -4px 0 #1264d6}.live-pill{animation:liveGlow 2s ease-in-out infinite}.courts-grid.courts-1{grid-template-columns:minmax(0,1fr);max-width:900px;width:100%;margin-inline:auto}.courts-grid.courts-2{grid-template-columns:repeat(2,minmax(0,1fr))}.courts-grid.courts-3{grid-template-columns:repeat(3,minmax(0,1fr))}.courts-grid.courts-4{grid-template-columns:repeat(2,minmax(0,1fr));grid-template-rows:repeat(2,minmax(0,1fr))}.court-card{--court-accent:#f4c84b;--court-glow:#f4c84b14;position:relative;background:radial-gradient(circle at 50% 0,var(--court-glow),transparent 48%),#0b111c;box-shadow:inset 0 0 34px var(--court-glow),0 10px 28px #0006;transition:border-color .2s,box-shadow .2s}.court-card:nth-child(2){--court-accent:#45a3ff;--court-glow:#258cff18}.court-card:nth-child(3){--court-accent:#f05672;--court-glow:#e8325715}.court-card:nth-child(4){--court-accent:#45d19b;--court-glow:#20b98014}.court-card:hover{border-color:var(--court-accent);box-shadow:inset 0 0 42px var(--court-glow),0 10px 32px #0008}.court-header{background:linear-gradient(180deg,var(--court-glow),#151e2c);border-top:2px solid var(--court-accent);border-bottom:1px solid #334155;box-shadow:inset 5px 0 #dc174b,inset -5px 0 #1264d6}.court-title{text-shadow:0 2px 8px #000,0 0 18px var(--court-glow)}.current-match{background:linear-gradient(180deg,var(--court-glow),transparent 36%)}.current-meta{filter:drop-shadow(0 3px 8px #0008)}.match-number{letter-spacing:-.04em}.match-weight{margin-top:.1rem}
.fighter{position:relative;z-index:1;overflow:hidden;border:1px solid #ffffff1c}.fighter-blue,.next-blue{background:#0755bd;box-shadow:inset 0 1px #ffffff2b}.fighter-red,.next-red{background:#c41442;box-shadow:inset 0 1px #ffffff2b}.versus-grid{position:relative;overflow:hidden}.vs-mark{position:relative;z-index:2}.upcoming-row{border:1px solid #263244}.upcoming-next{background:#161b20;border-color:#80651f}.next-player{border:1px solid #ffffff17}
.fighter-name,.next-player{max-width:100%;overflow:hidden;white-space:nowrap;line-height:1.15}.courts-2 .current-match{padding:clamp(.8rem,2vh,1.4rem)}.courts-2 .current-meta{margin-bottom:clamp(.75rem,2vh,1.25rem)}.courts-2 .current-meta>div:first-child{font-size:clamp(1.7rem,4vh,2.6rem)}.courts-2 .current-meta>div:nth-child(2){font-size:clamp(1.25rem,2.8vh,1.8rem)}.courts-2 .fighter{min-height:clamp(5rem,14vh,8rem)}.courts-2 .fighter>div{font-size:clamp(1.25rem,2.6vw,2rem)}.courts-3 .current-match{padding:clamp(.55rem,1.3vh,.9rem)}.courts-3 .fighter{min-height:clamp(3.7rem,10vh,6rem)}.courts-3 .fighter>div{font-size:clamp(1rem,1.65vw,1.5rem)}.courts-4 .current-match{padding:.45rem}.courts-4 .current-meta{margin-bottom:.4rem}.courts-4 .upcoming-block{display:flex;flex-direction:column;justify-content:center}.courts-4 .upcoming-list{grid-template-rows:1fr}.courts-4 .next-player{min-height:2.3rem}.courts-2 .next-player,.courts-3 .next-player{min-height:2.65rem}
.ovr-updated .court-card{animation:updateFlash .9s ease}.match-enter-active,.match-leave-active{transition:all .38s ease}.match-enter-from{opacity:0;transform:translateY(18px) scale(.98)}.match-leave-to{opacity:0;transform:translateY(-14px) scale(.98)}.flash-enter-active,.flash-leave-active{transition:all .3s}.flash-enter-from,.flash-leave-to{opacity:0;transform:translateY(-8px)}
@keyframes liveGlow{50%{box-shadow:0 0 14px #ef444433}}@keyframes updateFlash{25%{border-color:#34d399;box-shadow:0 0 24px #34d39944}}
.courts-grid.courts-2{grid-template-columns:minmax(0,1fr);grid-template-rows:repeat(2,minmax(0,1fr))}.courts-grid.courts-3{grid-template-columns:minmax(0,1fr);grid-template-rows:repeat(3,minmax(0,1fr))}.courts-grid.courts-4{grid-template-columns:minmax(0,1fr);grid-template-rows:repeat(4,minmax(0,1fr))}.courts-2 .court-card,.courts-3 .court-card,.courts-4 .court-card{display:grid;grid-template-columns:clamp(7rem,13vw,11rem) minmax(0,1.45fr) minmax(0,1fr);grid-template-rows:minmax(0,1fr)}.courts-2 .court-header,.courts-3 .court-header,.courts-4 .court-header{display:grid;place-items:center;border-bottom:0;border-left:1px solid #334155}.courts-2 .current-match,.courts-3 .current-match,.courts-4 .current-match{display:flex;min-width:0;flex-direction:column;justify-content:center}.courts-2 .upcoming-block,.courts-3 .upcoming-block,.courts-4 .upcoming-block{display:flex;min-width:0;flex-direction:column;justify-content:center;border-top:0;border-right:1px solid #334155}.courts-2 .upcoming-list,.courts-3 .upcoming-list,.courts-4 .upcoming-list{grid-template-rows:none}.courts-4 .court-title{font-size:clamp(.8rem,1.3vw,1.15rem)}
@media (max-width:700px){.courts-grid.courts-3{grid-template-columns:minmax(0,1fr);grid-template-rows:repeat(3,minmax(0,1fr));gap:.4rem}.courts-grid.courts-4{grid-template-columns:minmax(0,1fr);grid-template-rows:repeat(4,minmax(0,1fr));gap:.35rem}.court-title{font-size:1rem}.current-match{padding:.35rem}.current-meta{margin-bottom:.35rem}.upcoming-block{padding:.3rem}.scoreboard-header{padding-block:.4rem}.courts-3 .versus-grid{gap:.25rem;padding:.3rem}.courts-3 .fighter{padding-inline:.2rem}.courts-3 .vs-mark{font-size:.8rem}.courts-3 .upcoming-row{grid-template-columns:minmax(0,1fr) 2.7rem minmax(0,1fr);gap:.2rem}.courts-3 .court-card{grid-template-columns:6.5rem minmax(0,1.5fr) minmax(0,1fr)}.courts-3 .court-title{white-space:nowrap}.courts-3 .next-meta>div:first-child{font-size:.9rem}}
@media (max-height:720px){.scoreboard-header{padding-block:.35rem;margin-bottom:.35rem}.tkd-mark{height:2rem;width:2rem;font-size:.65rem}.court-header{padding-block:.3rem}.court-title{font-size:1rem}.current-match{padding:.3rem}.current-meta{display:flex;align-items:center;justify-content:center;gap:.45rem;margin-bottom:.25rem}.current-meta>div:first-child{font-size:1rem}.current-meta>div:nth-child(2){margin-top:0;font-size:.8rem}.current-meta>div:nth-child(3){display:none}.versus-grid{padding:.3rem}.fighter{min-height:2.25rem}.upcoming-block{overflow:hidden;padding:.25rem}.upcoming-block h3{margin-bottom:.15rem}.upcoming-list{gap:.2rem}.upcoming-row{padding:.15rem}.next-player{min-height:1.9rem;padding-block:.2rem}footer{display:none}.courts-3 .fighter{min-height:2.45rem}.courts-3 .fighter>div{font-size:.95rem}.courts-3 .next-player{min-height:1.9rem}.courts-4 .fighter{min-height:2.1rem}.courts-4 .upcoming-block h3{font-size:.6rem}}
@media (prefers-reduced-motion:reduce){*{animation:none!important;transition:none!important}}
</style>








